### ISSUE TITLE
Required docs [Sphinx]

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/church#1]
Very required the documentation, because at this moment we have only small [guidebook](https://github.com/lk-geimfari/church/blob/master/docs/README.md).

**Comment by Battleroid** [comment]
If it's alright with you, I'll give it a shot.

**Comment by lk-geimfari** [comment]
@Battleroid Thank you! Let me know about your final decision.

**Comment by arpit1997** [comment]
I would like to do these work. Let me know that if there is any need of updating the docStrings or not. One more question about the example, do you want examples included in the docs or not? :rocket:

**Comment by lk-geimfari** [comment]
@arpit1997 I think that docstrings is actual and recently updated. Yes, it would be good to include examples in the documentation. Everything should be in the 'docs' folder (root of repository). Thanks!

**Comment by Battleroid** [comment]
I'm going through and trying to put together the Sphinx documentation now. Some of the docstrings have very minor formatting issues so I'll fix those as well if that's ok.

**Comment by lk-geimfari** [comment]
@Battleroid Sorry for issues in docstrings. Thank you for your contribution!

**Comment by Battleroid** [comment]
Submitted pull request #29
