### ISSUE TITLE
Isn't this the same as FactoryBoy?

### ISSUE THREAD

**Issue by ruipacheco** [lk-geimfari/church#16]
The functionality seems to be pretty common to [FactoryBoy](https://factoryboy.readthedocs.io/en/latest/). Why a new library?

**Comment by lk-geimfari** [comment]
I never used FactoryBoy, but church supported more languages than Faker and work faster then Faker.

**Comment by ruipacheco** [comment]
FactoryBoy is a random data generator for tests. Church seems to serve the same purpose. And by languages do you mean natural languages or programming languages?

**Comment by lk-geimfari** [comment]
@ruipacheco Sorry. Not languages. `church` supported more specific data.

**Comment by lk-geimfari** [comment]
@ruipacheco At this moment church support only 4 languages: `en_us`, `de_de`, `fr_fr`, `ru_ru`. In the near future will be add support for Spanish.

**Comment by ruipacheco** [comment]
How does it generate data in those languages?

**Comment by lk-geimfari** [comment]
@ruipacheco [A small guidebook]( https://github.com/lk-geimfari/church/tree/master/docs)

**Comment by lk-geimfari** [comment]
@ruipacheco There are no recent changes, but nevertheless.

**Comment by ruipacheco** [comment]
Not what I meant. How does Church know that a given string is a valid Russian surname?

**Comment by lk-geimfari** [comment]
Oh. We have special folder for all languages. For Russia is 'ru_ru' and all data in ru_ru folder in russian languages.

```python
from church import Personal

person = Personal('ru_ru')

print(person.full_name(gender='m'))
# Output: Василий Петров
```
