### ISSUE TITLE
Add the ability to test all locales at once.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/church#28]
We need test all locales at one moment without manual changes file `tests.py`. Because by default `tests.py` will test only `en` locale. If we want to check other locales then we need manually change value of [LANG](https://github.com/lk-geimfari/church/blob/master/tests.py#L20) in file[ tests.py ](https://github.com/lk-geimfari/church/blob/master/tests.py)and it's not good. One of the best solution is a [pytest.fixture](http://doc.pytest.org/en/latest/fixture.html)

So if anyone can help us with this problem, please let me know. Thanks!

**Comment by Battleroid** [comment]
I'm looking at this right now. I think it can be done with `unittest` alone using the list of locales and a custom `TestSuite`.

**Comment by lk-geimfari** [comment]
@Battleroid Oh, great!. I'll wait for your PR, if you can do it.

**Comment by Battleroid** [comment]
I'll certainly give it a try!

**Comment by lk-geimfari** [comment]
@Battleroid Deal!

**Comment by Battleroid** [comment]
I submitted my attempt at PR #43.

**Comment by lk-geimfari** [comment]
@Battleroid Great work! Thank you!
