### ISSUE TITLE
Address.street_address() not working

### ISSUE THREAD

**Issue by memilanuk** [lk-geimfari/church#32]
Trying to use `church`, ran into a snag with the following:

    >>> from church import Address

    >>> address = Address('en')

    >>> address.street_address()
    Traceback (most recent call last):
      File "<input>", line 1, in <module>
    AttributeError: 'Address' object has no attribute 'street_address'

...which seems pretty much identical to what is shown here (http://church.readthedocs.io/en/latest/guide.html#address):

    address = Address('en')
    ...
    # Get a random address.
    # 786 Clinton Lane
    street_address = address.street_address()

Thanks!

**Comment by lk-geimfari** [comment]
@memilanuk The problem is that the documentation is a bit outdated. I will update documentation soon. So, if you want to get address use follow format:

```
>>> from church import Address

>>> address = Address('en')

>>> address.address()
```

**Comment by memilanuk** [comment]
Ah.  Gotcha, thanks!

**Comment by lk-geimfari** [comment]
@memilanuk I am glad to help!
