### ISSUE TITLE
Refusal of unstructured data storage.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/church#36]
I think that text files as a storage is not a better solution. We can use JSON for structured data storage.

Example:

```
.
├── personal.json
├── business.json
├── datetime.json
├── food.json
├── address.json
├── science.json
├── text.json
```
We need to jsonify all data for all locales. @sobolevn what do you think about this idea?

**Comment by sobolevn** [comment]
> I think that text files as a storage is not a better solution.

What are your arguments?

It seems to me that using one file will make it unreadable for a human.

**Comment by sammyshj** [comment]
@lk-geimfari I want to work on this. Where should I look at for storing the structured data?

**Comment by lk-geimfari** [comment]
@sammyshj Today, I will upload dev-brunch.

**Comment by lk-geimfari** [comment]
It's done!
