### ISSUE TITLE
Add abbreviation to State field

### ISSUE THREAD

**Issue by memilanuk** [lk-geimfari/church#38]
Add option for abbreviation of state name i.e. something like:

`address.state(abbrev=True)`

to return 'WA' for state, vs. 'Washington'.  

Probably want to do something similar for states/provinces in other countries?

**Comment by lk-geimfari** [comment]
I think that it's possible. We will add this functionality soon. Thanks!

**Comment by lk-geimfari** [comment]
@memilanuk [It's](https://github.com/lk-geimfari/church/commit/854c6be106897ff9ba0aaa7dacfa8e8749a5eeaf) done!
