### ISSUE TITLE
Wrong display of a french address

### ISSUE THREAD

**Issue by mirelsol** [lk-geimfari/church#45]
```
>>> from church import Address
>>> addr = Address('fr')
>>> addr.address()
'371 Bezout Rue du'
```

The output should be:
'371 Rue du Bezout'

**Comment by lk-geimfari** [comment]
@mirelsol Thank you for feedback. I will fix it.

**Comment by mirelsol** [comment]
@lk-geimfari in fact I already fixed it. I cloned the project, created a branch then committed my changes. But when I want to push it I get 'permission denied'. What am I missing? Sorry for this dummy question...

**Comment by lk-geimfari** [comment]
@mirelsol I don't see the `church` in your repositories. Maybe you don't forked the 'church'.

**Comment by mirelsol** [comment]
Ok thanks, sorry I didn't see that you already fixed it.
