### ISSUE TITLE
Offensive name

### ISSUE THREAD

**Issue by Offirmo** [lk-geimfari/church#6]
sorry. I get the joke, but it's a bit offensive. :cry:

**Comment by Offirmo** [comment]
I don't want to complain without offering suggestions:
- pinocchio (or pynocchio ;)
- (looking for more)

**Comment by lk-geimfari** [comment]
@Offirmo Jesus Christ! Are you serious?

**Comment by Offirmo** [comment]
I understand you want to make a joke, but "Church as a generator of fake data" is derogatory. You may want to check http://contributor-covenant.org/ (emphasis mine)

> a harassment-free experience for everyone, regardless of age, body
> size, disability, ethnicity, gender identity and expression, level of experience,
> nationality, personal appearance, race, **religion**, or sexual identity and
> orientation.

Words and how we use them is more serious that you may think. I suggest you see this incident as a learning experience.

You may also want to check http://geekfeminism.wikia.com/wiki/Geek_Feminism_Wiki for an example of struggle for ending harassment about one's specifity.

I'm sure you care about being nice and respectful to everyone. Now is your time to shine ! There are so many naming possibilities...

**Comment by Offirmo** [comment]
In case you wonder, it's very easy to rename a git repo. Just go to the "settings" tab.

**Comment by lk-geimfari** [comment]
@Offirmo [Some interesting things](https://en.wikipedia.org/wiki/Freedom_of_speech). If you are offended by the name of this library, just do not use it, okay? I like this library, i will use this library and i will use this name. You can use another library and ignore 'church'. It's so simple.

**Comment by Offirmo** [comment]
That's interesting https://www.ashedryden.com/blog/codes-of-conduct-101-faq#cocfaqcensorship

**Comment by Offirmo** [comment]
I'll even quote it for you

ISN'T THIS CENSORSHIP? WHAT ABOUT FREE SPEECH?
Free speech laws do not apply to harassment and assault and furthermore don't apply to individuals that are not representing the government. The point at which a person is actively harming another individual is not only not free speech, but it is against the law.

You can read more about the first amendment on Wikipedia.

DOES THIS MEAN I CAN'T SWEAR OR MAKE JOKES?
Whether or not you can swear is entirely up to the individual event. Some events allow the attendance of children, others take place in either more conservative areas or in venues that require a certain level of professionalism. Consult a conference organizer if you are worried about swearing, especially if you intend to do so in a talk.

You are more than welcome to make jokes as long as they don't create a harassing or dangerous atmosphere for other attendees. If a joke you are considering making may violate the code of conduct, perhaps that isn't the type of joke you should be making in public around strangers or potentially at all.

**Comment by lk-geimfari** [comment]
If someone wants to take part in the holy war, then it's time.

**Comment by csik** [comment]
See cf "Prayer Gauge Debate" p. 784 http://users.uoa.gr/~mpatin/Modern%20Science/Gieryn.pdf

**Comment by waynew** [comment]
I'm religious and I don't find this name offensive at all.

**Comment by lk-geimfari** [comment]
Library has been renamed.

**Comment by Offirmo** [comment]
:+1:

**Comment by Noiwex** [comment]
god this is stupid

**Comment by lk-geimfari** [comment]
@Noiwex Absolutely agree, but what can I do...?

**Comment by neoascetic** [comment]
Hello, my name is Elizabeth, and current name of the library is a little bit offensive. 😢

**Comment by beshkenadze** [comment]
@lk-geimfari 
Hi, my wife's name is Elizabeth. I offended the idea that she can tell me the fake data :(
;)

**Comment by Noiwex** [comment]
@lk-geimfari ignore trolls?

**Comment by neoascetic** [comment]
Don't you think @Offirmo is troll as well?

**Comment by wikkiewikkie** [comment]
@lk-gimfari  My brother was killed by a snake, and Python is offensive to me.  Please re-write in an inoffensive language like brainfuck.

**Comment by vassilevsky** [comment]
Obvious choice for the name is "Trump" btw

**Comment by lk-geimfari** [comment]
Okay, okay guys. We all know that the church is above all. We can insult anyone, but not religious or church.

**Comment by lk-geimfari** [comment]
@Noiwex No, I just wrote new features for @neoascetic .

**Comment by lk-geimfari** [comment]
It's funny, but similar incident has happened again. [factory_girl](https://github.com/thoughtbot/factory_bot/issues/921) was renamed.
